"""Add status to goals

Revision ID: 3398477c0113
Revises: c9d2a6a61a9f
Create Date: 2026-05-16 21:31:44.480000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3398477c0113'
down_revision: Union[str, Sequence[str], None] = 'c9d2a6a61a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'status')
    # ### end Alembic commands ###
